source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ShareReader_Example', :exclusive => true do
  pod "ShareReader", :path => "../"
end

target 'ShareReader_Tests', :exclusive => true do
  pod "ShareReader", :path => "../"

  
end
